# Generated by Django 2.0.7 on 2019-02-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.PositiveIntegerField(default=7, null=True, verbose_name='建议学习周期(days)'),
        ),
    ]
