# Generated by Django 2.0.7 on 2019-02-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190228_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.PositiveIntegerField(null=True, verbose_name='建议学习周期(days)'),
        ),
    ]
