# Generated by Django 2.0.7 on 2019-02-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190228_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.IntegerField(null=True, verbose_name='建议学习周期(days)'),
        ),
    ]
