# Generated by Django 2.0.7 on 2019-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190228_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oftenaskedquestion',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
