# Generated by Django 2.0.7 on 2019-02-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190228_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
    ]
