# Generated by Django 2.0.7 on 2019-02-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190228_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='free_trail',
            field=models.IntegerField(verbose_name='1可以观看，0不可以观看'),
        ),
    ]
