# Generated by Django 2.0.7 on 2019-02-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190228_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='homework',
            name='order',
            field=models.SmallIntegerField(help_text='同一课程的每个作业之前的order值间隔1-2个数', verbose_name='作业顺序'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='recommend_period',
            field=models.SmallIntegerField(default=7, verbose_name='推荐完成周期(天)'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='scholarship_value',
            field=models.SmallIntegerField(verbose_name='为该作业分配的奖学金(贝里)'),
        ),
    ]
