# Generated by Django 2.0.7 on 2019-02-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190228_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
