# Generated by Django 2.0.7 on 2019-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190308_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='object_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
