# Generated by Django 2.0.7 on 2019-03-15 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190308_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthtoken',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
