# Generated by Django 2.0.7 on 2019-03-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userauthtoken_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthtoken',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
